name = 'mysvc'
command = ['gunicorn', '-b', '0.0.0.0:8080', 'httpbin:app', '-k', 'gevent']

[image]
image = 'docker.io/kong/httpbin:0.1.0'

[[environment]]
name = 'GREET'
value = '{{ secrets.GREET_TYPE }}'

[[ports]]
port = 8080
type = 'http'
publish = true

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128

[[resources.storage]]
name = 'storage1'
capacity = 1
path = '/var/lib/storage1'
