// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package graphql

import (
	"context"
	"net/http"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli *http.Client, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type QueryRoot struct {
	App                                     *Apps                                   "json:\"app,omitempty\" graphql:\"app\""
	AppSecrets                              []*ConfigEnvironmentVariable            "json:\"appSecrets\" graphql:\"appSecrets\""
	AppState                                *AppStates                              "json:\"appState,omitempty\" graphql:\"appState\""
	AppStateHistories                       []*AppStateHistory                      "json:\"appStateHistories\" graphql:\"appStateHistories\""
	AppStateHistory                         *AppStateHistory                        "json:\"appStateHistory,omitempty\" graphql:\"appStateHistory\""
	AppStateHistoryAggregate                AppStateHistoryAggregate                "json:\"appStateHistoryAggregate\" graphql:\"appStateHistoryAggregate\""
	AppStates                               []*AppStates                            "json:\"appStates\" graphql:\"appStates\""
	AppStatesAggregate                      AppStatesAggregate                      "json:\"appStatesAggregate\" graphql:\"appStatesAggregate\""
	Apps                                    []*Apps                                 "json:\"apps\" graphql:\"apps\""
	AppsAggregate                           AppsAggregate                           "json:\"appsAggregate\" graphql:\"appsAggregate\""
	AppsSecrets                             []*ConfigAppSecrets                     "json:\"appsSecrets,omitempty\" graphql:\"appsSecrets\""
	AuthProvider                            *AuthProviders                          "json:\"authProvider,omitempty\" graphql:\"authProvider\""
	AuthProviderRequest                     *AuthProviderRequests                   "json:\"authProviderRequest,omitempty\" graphql:\"authProviderRequest\""
	AuthProviderRequests                    []*AuthProviderRequests                 "json:\"authProviderRequests\" graphql:\"authProviderRequests\""
	AuthProviderRequestsAggregate           AuthProviderRequestsAggregate           "json:\"authProviderRequestsAggregate\" graphql:\"authProviderRequestsAggregate\""
	AuthProviders                           []*AuthProviders                        "json:\"authProviders\" graphql:\"authProviders\""
	AuthProvidersAggregate                  AuthProvidersAggregate                  "json:\"authProvidersAggregate\" graphql:\"authProvidersAggregate\""
	AuthRefreshToken                        *AuthRefreshTokens                      "json:\"authRefreshToken,omitempty\" graphql:\"authRefreshToken\""
	AuthRefreshTokens                       []*AuthRefreshTokens                    "json:\"authRefreshTokens\" graphql:\"authRefreshTokens\""
	AuthRefreshTokensAggregate              AuthRefreshTokensAggregate              "json:\"authRefreshTokensAggregate\" graphql:\"authRefreshTokensAggregate\""
	AuthRole                                *AuthRoles                              "json:\"authRole,omitempty\" graphql:\"authRole\""
	AuthRoles                               []*AuthRoles                            "json:\"authRoles\" graphql:\"authRoles\""
	AuthRolesAggregate                      AuthRolesAggregate                      "json:\"authRolesAggregate\" graphql:\"authRolesAggregate\""
	AuthUserProvider                        *AuthUserProviders                      "json:\"authUserProvider,omitempty\" graphql:\"authUserProvider\""
	AuthUserProviders                       []*AuthUserProviders                    "json:\"authUserProviders\" graphql:\"authUserProviders\""
	AuthUserProvidersAggregate              AuthUserProvidersAggregate              "json:\"authUserProvidersAggregate\" graphql:\"authUserProvidersAggregate\""
	AuthUserRole                            *AuthUserRoles                          "json:\"authUserRole,omitempty\" graphql:\"authUserRole\""
	AuthUserRoles                           []*AuthUserRoles                        "json:\"authUserRoles\" graphql:\"authUserRoles\""
	AuthUserRolesAggregate                  AuthUserRolesAggregate                  "json:\"authUserRolesAggregate\" graphql:\"authUserRolesAggregate\""
	AuthUserSecurityKey                     *AuthUserSecurityKeys                   "json:\"authUserSecurityKey,omitempty\" graphql:\"authUserSecurityKey\""
	AuthUserSecurityKeys                    []*AuthUserSecurityKeys                 "json:\"authUserSecurityKeys\" graphql:\"authUserSecurityKeys\""
	AuthUserSecurityKeysAggregate           AuthUserSecurityKeysAggregate           "json:\"authUserSecurityKeysAggregate\" graphql:\"authUserSecurityKeysAggregate\""
	AuthMigrations                          []*AuthMigrations                       "json:\"auth_migrations\" graphql:\"auth_migrations\""
	AuthMigrationsAggregate                 AuthMigrationsAggregate                 "json:\"auth_migrations_aggregate\" graphql:\"auth_migrations_aggregate\""
	AuthMigrationsByPk                      *AuthMigrations                         "json:\"auth_migrations_by_pk,omitempty\" graphql:\"auth_migrations_by_pk\""
	Backup                                  *Backups                                "json:\"backup,omitempty\" graphql:\"backup\""
	Backups                                 []*Backups                              "json:\"backups\" graphql:\"backups\""
	BackupsAggregate                        BackupsAggregate                        "json:\"backupsAggregate\" graphql:\"backupsAggregate\""
	BillingDedicatedCompute                 *BillingDedicatedCompute                "json:\"billingDedicatedCompute,omitempty\" graphql:\"billingDedicatedCompute\""
	BillingDedicatedComputeAggregate        BillingDedicatedComputeAggregate        "json:\"billingDedicatedComputeAggregate\" graphql:\"billingDedicatedComputeAggregate\""
	BillingDedicatedComputeReport           *BillingDedicatedComputeReports         "json:\"billingDedicatedComputeReport,omitempty\" graphql:\"billingDedicatedComputeReport\""
	BillingDedicatedComputeReports          []*BillingDedicatedComputeReports       "json:\"billingDedicatedComputeReports\" graphql:\"billingDedicatedComputeReports\""
	BillingDedicatedComputeReportsAggregate BillingDedicatedComputeReportsAggregate "json:\"billingDedicatedComputeReportsAggregate\" graphql:\"billingDedicatedComputeReportsAggregate\""
	BillingDedicatedComputes                []*BillingDedicatedCompute              "json:\"billingDedicatedComputes\" graphql:\"billingDedicatedComputes\""
	BillingDummy                            bool                                    "json:\"billingDummy\" graphql:\"billingDummy\""
	BillingSubscription                     *BillingSubscriptions                   "json:\"billingSubscription,omitempty\" graphql:\"billingSubscription\""
	BillingSubscriptions                    []*BillingSubscriptions                 "json:\"billingSubscriptions\" graphql:\"billingSubscriptions\""
	BillingSubscriptionsAggregate           BillingSubscriptionsAggregate           "json:\"billingSubscriptionsAggregate\" graphql:\"billingSubscriptionsAggregate\""
	Bucket                                  *Buckets                                "json:\"bucket,omitempty\" graphql:\"bucket\""
	Buckets                                 []*Buckets                              "json:\"buckets\" graphql:\"buckets\""
	BucketsAggregate                        BucketsAggregate                        "json:\"bucketsAggregate\" graphql:\"bucketsAggregate\""
	CliToken                                *CliTokens                              "json:\"cliToken,omitempty\" graphql:\"cliToken\""
	CliTokens                               []*CliTokens                            "json:\"cliTokens\" graphql:\"cliTokens\""
	CliTokensAggregate                      CliTokensAggregate                      "json:\"cliTokensAggregate\" graphql:\"cliTokensAggregate\""
	Config                                  *ConfigConfig                           "json:\"config,omitempty\" graphql:\"config\""
	Configs                                 []*ConfigAppConfig                      "json:\"configs\" graphql:\"configs\""
	Continents                              []*Continents                           "json:\"continents\" graphql:\"continents\""
	ContinentsAggregate                     ContinentsAggregate                     "json:\"continents_aggregate\" graphql:\"continents_aggregate\""
	ContinentsByPk                          *Continents                             "json:\"continents_by_pk,omitempty\" graphql:\"continents_by_pk\""
	Countries                               []*Countries                            "json:\"countries\" graphql:\"countries\""
	CountriesAggregate                      CountriesAggregate                      "json:\"countries_aggregate\" graphql:\"countries_aggregate\""
	CountriesByPk                           *Countries                              "json:\"countries_by_pk,omitempty\" graphql:\"countries_by_pk\""
	Deployment                              *Deployments                            "json:\"deployment,omitempty\" graphql:\"deployment\""
	DeploymentLog                           *DeploymentLogs                         "json:\"deploymentLog,omitempty\" graphql:\"deploymentLog\""
	DeploymentLogs                          []*DeploymentLogs                       "json:\"deploymentLogs\" graphql:\"deploymentLogs\""
	DeploymentLogsAggregate                 DeploymentLogsAggregate                 "json:\"deploymentLogsAggregate\" graphql:\"deploymentLogsAggregate\""
	Deployments                             []*Deployments                          "json:\"deployments\" graphql:\"deployments\""
	DeploymentsAggregate                    DeploymentsAggregate                    "json:\"deploymentsAggregate\" graphql:\"deploymentsAggregate\""
	FeatureFlag                             *FeatureFlags                           "json:\"featureFlag,omitempty\" graphql:\"featureFlag\""
	FeatureFlags                            []*FeatureFlags                         "json:\"featureFlags\" graphql:\"featureFlags\""
	FeatureFlagsAggregate                   FeatureFlagsAggregate                   "json:\"featureFlagsAggregate\" graphql:\"featureFlagsAggregate\""
	Feedback                                []*Feedback                             "json:\"feedback\" graphql:\"feedback\""
	FeedbackAggreggate                      FeedbackAggregate                       "json:\"feedbackAggreggate\" graphql:\"feedbackAggreggate\""
	FeedbackOne                             *Feedback                               "json:\"feedbackOne,omitempty\" graphql:\"feedbackOne\""
	File                                    *Files                                  "json:\"file,omitempty\" graphql:\"file\""
	Files                                   []*Files                                "json:\"files\" graphql:\"files\""
	FilesAggregate                          FilesAggregate                          "json:\"filesAggregate\" graphql:\"filesAggregate\""
	GetCPUSecondsUsage                      Metrics                                 "json:\"getCPUSecondsUsage\" graphql:\"getCPUSecondsUsage\""
	GetEgressVolume                         Metrics                                 "json:\"getEgressVolume\" graphql:\"getEgressVolume\""
	GetFunctionsInvocations                 Metrics                                 "json:\"getFunctionsInvocations\" graphql:\"getFunctionsInvocations\""
	GetLogsVolume                           Metrics                                 "json:\"getLogsVolume\" graphql:\"getLogsVolume\""
	GetPostgresVolumeCapacity               Metrics                                 "json:\"getPostgresVolumeCapacity\" graphql:\"getPostgresVolumeCapacity\""
	GetPostgresVolumeUsage                  Metrics                                 "json:\"getPostgresVolumeUsage\" graphql:\"getPostgresVolumeUsage\""
	GetTotalRequests                        Metrics                                 "json:\"getTotalRequests\" graphql:\"getTotalRequests\""
	GithubAppInstallation                   *GithubAppInstallations                 "json:\"githubAppInstallation,omitempty\" graphql:\"githubAppInstallation\""
	GithubAppInstallations                  []*GithubAppInstallations               "json:\"githubAppInstallations\" graphql:\"githubAppInstallations\""
	GithubAppInstallationsAggregate         GithubAppInstallationsAggregate         "json:\"githubAppInstallationsAggregate\" graphql:\"githubAppInstallationsAggregate\""
	GithubRepositories                      []*GithubRepositories                   "json:\"githubRepositories\" graphql:\"githubRepositories\""
	GithubRepositoriesAggregate             GithubRepositoriesAggregate             "json:\"githubRepositoriesAggregate\" graphql:\"githubRepositoriesAggregate\""
	GithubRepository                        *GithubRepositories                     "json:\"githubRepository,omitempty\" graphql:\"githubRepository\""
	Logs                                    []*Log                                  "json:\"logs\" graphql:\"logs\""
	PaymentMethod                           *PaymentMethods                         "json:\"paymentMethod,omitempty\" graphql:\"paymentMethod\""
	PaymentMethods                          []*PaymentMethods                       "json:\"paymentMethods\" graphql:\"paymentMethods\""
	PaymentMethodsAggregate                 PaymentMethodsAggregate                 "json:\"paymentMethodsAggregate\" graphql:\"paymentMethodsAggregate\""
	Plan                                    *Plans                                  "json:\"plan,omitempty\" graphql:\"plan\""
	Plans                                   []*Plans                                "json:\"plans\" graphql:\"plans\""
	PlansAggregate                          PlansAggregate                          "json:\"plansAggregate\" graphql:\"plansAggregate\""
	Regions                                 []*Regions                              "json:\"regions\" graphql:\"regions\""
	RegionsAggregate                        RegionsAggregate                        "json:\"regions_aggregate\" graphql:\"regions_aggregate\""
	RegionsByPk                             *Regions                                "json:\"regions_by_pk,omitempty\" graphql:\"regions_by_pk\""
	StatsLiveApps                           StatsLiveApps                           "json:\"statsLiveApps\" graphql:\"statsLiveApps\""
	SystemConfig                            *ConfigSystemConfig                     "json:\"systemConfig,omitempty\" graphql:\"systemConfig\""
	SystemConfigs                           []*ConfigAppSystemConfig                "json:\"systemConfigs\" graphql:\"systemConfigs\""
	User                                    *Users                                  "json:\"user,omitempty\" graphql:\"user\""
	Users                                   []*Users                                "json:\"users\" graphql:\"users\""
	UsersAggregate                          UsersAggregate                          "json:\"usersAggregate\" graphql:\"usersAggregate\""
	Workspace                               *Workspaces                             "json:\"workspace,omitempty\" graphql:\"workspace\""
	WorkspaceMember                         *WorkspaceMembers                       "json:\"workspaceMember,omitempty\" graphql:\"workspaceMember\""
	WorkspaceMemberInvite                   *WorkspaceMemberInvites                 "json:\"workspaceMemberInvite,omitempty\" graphql:\"workspaceMemberInvite\""
	WorkspaceMemberInvites                  []*WorkspaceMemberInvites               "json:\"workspaceMemberInvites\" graphql:\"workspaceMemberInvites\""
	WorkspaceMemberInvitesAggregate         WorkspaceMemberInvitesAggregate         "json:\"workspaceMemberInvitesAggregate\" graphql:\"workspaceMemberInvitesAggregate\""
	WorkspaceMembers                        []*WorkspaceMembers                     "json:\"workspaceMembers\" graphql:\"workspaceMembers\""
	WorkspaceMembersAggregate               WorkspaceMembersAggregate               "json:\"workspaceMembersAggregate\" graphql:\"workspaceMembersAggregate\""
	Workspaces                              []*Workspaces                           "json:\"workspaces\" graphql:\"workspaces\""
	WorkspacesAggregate                     WorkspacesAggregate                     "json:\"workspacesAggregate\" graphql:\"workspacesAggregate\""
}
type MutationRoot struct {
	BackupAllApplicationsDatabase                       []*BackupResultsItem                              "json:\"backupAllApplicationsDatabase\" graphql:\"backupAllApplicationsDatabase\""
	BackupApplicationDatabase                           BackupResult                                      "json:\"backupApplicationDatabase\" graphql:\"backupApplicationDatabase\""
	BillingFinishSubscription                           bool                                              "json:\"billingFinishSubscription\" graphql:\"billingFinishSubscription\""
	BillingFixSubscriptions                             bool                                              "json:\"billingFixSubscriptions\" graphql:\"billingFixSubscriptions\""
	BillingReportDedicatedCompute                       bool                                              "json:\"billingReportDedicatedCompute\" graphql:\"billingReportDedicatedCompute\""
	BillingUpdateAndReportDedicatedComputeReports       bool                                              "json:\"billingUpdateAndReportDedicatedComputeReports\" graphql:\"billingUpdateAndReportDedicatedComputeReports\""
	BillingUpdateDedicatedCompute                       bool                                              "json:\"billingUpdateDedicatedCompute\" graphql:\"billingUpdateDedicatedCompute\""
	BillingUpdateDedicatedComputeReports                bool                                              "json:\"billingUpdateDedicatedComputeReports\" graphql:\"billingUpdateDedicatedComputeReports\""
	DeleteApp                                           *Apps                                             "json:\"deleteApp,omitempty\" graphql:\"deleteApp\""
	DeleteAppState                                      *AppStates                                        "json:\"deleteAppState,omitempty\" graphql:\"deleteAppState\""
	DeleteAppStateHistories                             *AppStateHistoryMutationResponse                  "json:\"deleteAppStateHistories,omitempty\" graphql:\"deleteAppStateHistories\""
	DeleteAppStateHistory                               *AppStateHistory                                  "json:\"deleteAppStateHistory,omitempty\" graphql:\"deleteAppStateHistory\""
	DeleteAppStates                                     *AppStatesMutationResponse                        "json:\"deleteAppStates,omitempty\" graphql:\"deleteAppStates\""
	DeleteApps                                          *AppsMutationResponse                             "json:\"deleteApps,omitempty\" graphql:\"deleteApps\""
	DeleteAuthProvider                                  *AuthProviders                                    "json:\"deleteAuthProvider,omitempty\" graphql:\"deleteAuthProvider\""
	DeleteAuthProviderRequest                           *AuthProviderRequests                             "json:\"deleteAuthProviderRequest,omitempty\" graphql:\"deleteAuthProviderRequest\""
	DeleteAuthProviderRequests                          *AuthProviderRequestsMutationResponse             "json:\"deleteAuthProviderRequests,omitempty\" graphql:\"deleteAuthProviderRequests\""
	DeleteAuthProviders                                 *AuthProvidersMutationResponse                    "json:\"deleteAuthProviders,omitempty\" graphql:\"deleteAuthProviders\""
	DeleteAuthRefreshToken                              *AuthRefreshTokens                                "json:\"deleteAuthRefreshToken,omitempty\" graphql:\"deleteAuthRefreshToken\""
	DeleteAuthRefreshTokens                             *AuthRefreshTokensMutationResponse                "json:\"deleteAuthRefreshTokens,omitempty\" graphql:\"deleteAuthRefreshTokens\""
	DeleteAuthRole                                      *AuthRoles                                        "json:\"deleteAuthRole,omitempty\" graphql:\"deleteAuthRole\""
	DeleteAuthRoles                                     *AuthRolesMutationResponse                        "json:\"deleteAuthRoles,omitempty\" graphql:\"deleteAuthRoles\""
	DeleteAuthUserProvider                              *AuthUserProviders                                "json:\"deleteAuthUserProvider,omitempty\" graphql:\"deleteAuthUserProvider\""
	DeleteAuthUserProviders                             *AuthUserProvidersMutationResponse                "json:\"deleteAuthUserProviders,omitempty\" graphql:\"deleteAuthUserProviders\""
	DeleteAuthUserRole                                  *AuthUserRoles                                    "json:\"deleteAuthUserRole,omitempty\" graphql:\"deleteAuthUserRole\""
	DeleteAuthUserRoles                                 *AuthUserRolesMutationResponse                    "json:\"deleteAuthUserRoles,omitempty\" graphql:\"deleteAuthUserRoles\""
	DeleteAuthUserSecurityKey                           *AuthUserSecurityKeys                             "json:\"deleteAuthUserSecurityKey,omitempty\" graphql:\"deleteAuthUserSecurityKey\""
	DeleteAuthUserSecurityKeys                          *AuthUserSecurityKeysMutationResponse             "json:\"deleteAuthUserSecurityKeys,omitempty\" graphql:\"deleteAuthUserSecurityKeys\""
	DeleteBackup                                        *Backups                                          "json:\"deleteBackup,omitempty\" graphql:\"deleteBackup\""
	DeleteBackups                                       *BackupsMutationResponse                          "json:\"deleteBackups,omitempty\" graphql:\"deleteBackups\""
	DeleteBucket                                        *Buckets                                          "json:\"deleteBucket,omitempty\" graphql:\"deleteBucket\""
	DeleteBuckets                                       *BucketsMutationResponse                          "json:\"deleteBuckets,omitempty\" graphql:\"deleteBuckets\""
	DeleteCliToken                                      *CliTokens                                        "json:\"deleteCliToken,omitempty\" graphql:\"deleteCliToken\""
	DeleteCliTokens                                     *CliTokensMutationResponse                        "json:\"deleteCliTokens,omitempty\" graphql:\"deleteCliTokens\""
	DeleteConfig                                        *ConfigConfig                                     "json:\"deleteConfig,omitempty\" graphql:\"deleteConfig\""
	DeleteDeployment                                    *Deployments                                      "json:\"deleteDeployment,omitempty\" graphql:\"deleteDeployment\""
	DeleteDeploymentLog                                 *DeploymentLogs                                   "json:\"deleteDeploymentLog,omitempty\" graphql:\"deleteDeploymentLog\""
	DeleteDeploymentLogs                                *DeploymentLogsMutationResponse                   "json:\"deleteDeploymentLogs,omitempty\" graphql:\"deleteDeploymentLogs\""
	DeleteDeployments                                   *DeploymentsMutationResponse                      "json:\"deleteDeployments,omitempty\" graphql:\"deleteDeployments\""
	DeleteFeatureFlag                                   *FeatureFlags                                     "json:\"deleteFeatureFlag,omitempty\" graphql:\"deleteFeatureFlag\""
	DeleteFeatureFlags                                  *FeatureFlagsMutationResponse                     "json:\"deleteFeatureFlags,omitempty\" graphql:\"deleteFeatureFlags\""
	DeleteFeedback                                      *FeedbackMutationResponse                         "json:\"deleteFeedback,omitempty\" graphql:\"deleteFeedback\""
	DeleteFeedbackOne                                   *Feedback                                         "json:\"deleteFeedbackOne,omitempty\" graphql:\"deleteFeedbackOne\""
	DeleteFile                                          *Files                                            "json:\"deleteFile,omitempty\" graphql:\"deleteFile\""
	DeleteFiles                                         *FilesMutationResponse                            "json:\"deleteFiles,omitempty\" graphql:\"deleteFiles\""
	DeleteGithubAppInstallation                         *GithubAppInstallations                           "json:\"deleteGithubAppInstallation,omitempty\" graphql:\"deleteGithubAppInstallation\""
	DeleteGithubAppInstallations                        *GithubAppInstallationsMutationResponse           "json:\"deleteGithubAppInstallations,omitempty\" graphql:\"deleteGithubAppInstallations\""
	DeleteGithubRepositories                            *GithubRepositoriesMutationResponse               "json:\"deleteGithubRepositories,omitempty\" graphql:\"deleteGithubRepositories\""
	DeleteGithubRepository                              *GithubRepositories                               "json:\"deleteGithubRepository,omitempty\" graphql:\"deleteGithubRepository\""
	DeletePaymentMethod                                 *PaymentMethods                                   "json:\"deletePaymentMethod,omitempty\" graphql:\"deletePaymentMethod\""
	DeletePaymentMethods                                *PaymentMethodsMutationResponse                   "json:\"deletePaymentMethods,omitempty\" graphql:\"deletePaymentMethods\""
	DeletePlan                                          *Plans                                            "json:\"deletePlan,omitempty\" graphql:\"deletePlan\""
	DeletePlans                                         *PlansMutationResponse                            "json:\"deletePlans,omitempty\" graphql:\"deletePlans\""
	DeleteSecret                                        ConfigEnvironmentVariable                         "json:\"deleteSecret\" graphql:\"deleteSecret\""
	DeleteUser                                          *Users                                            "json:\"deleteUser,omitempty\" graphql:\"deleteUser\""
	DeleteUsers                                         *UsersMutationResponse                            "json:\"deleteUsers,omitempty\" graphql:\"deleteUsers\""
	DeleteWorkspace                                     *Workspaces                                       "json:\"deleteWorkspace,omitempty\" graphql:\"deleteWorkspace\""
	DeleteWorkspaceMember                               *WorkspaceMembers                                 "json:\"deleteWorkspaceMember,omitempty\" graphql:\"deleteWorkspaceMember\""
	DeleteWorkspaceMemberInvite                         *WorkspaceMemberInvites                           "json:\"deleteWorkspaceMemberInvite,omitempty\" graphql:\"deleteWorkspaceMemberInvite\""
	DeleteWorkspaceMemberInvites                        *WorkspaceMemberInvitesMutationResponse           "json:\"deleteWorkspaceMemberInvites,omitempty\" graphql:\"deleteWorkspaceMemberInvites\""
	DeleteWorkspaceMembers                              *WorkspaceMembersMutationResponse                 "json:\"deleteWorkspaceMembers,omitempty\" graphql:\"deleteWorkspaceMembers\""
	DeleteWorkspaces                                    *WorkspacesMutationResponse                       "json:\"deleteWorkspaces,omitempty\" graphql:\"deleteWorkspaces\""
	DeleteAuthMigrations                                *AuthMigrationsMutationResponse                   "json:\"delete_auth_migrations,omitempty\" graphql:\"delete_auth_migrations\""
	DeleteAuthMigrationsByPk                            *AuthMigrations                                   "json:\"delete_auth_migrations_by_pk,omitempty\" graphql:\"delete_auth_migrations_by_pk\""
	DeleteContinents                                    *ContinentsMutationResponse                       "json:\"delete_continents,omitempty\" graphql:\"delete_continents\""
	DeleteContinentsByPk                                *Continents                                       "json:\"delete_continents_by_pk,omitempty\" graphql:\"delete_continents_by_pk\""
	DeleteCountries                                     *CountriesMutationResponse                        "json:\"delete_countries,omitempty\" graphql:\"delete_countries\""
	DeleteCountriesByPk                                 *Countries                                        "json:\"delete_countries_by_pk,omitempty\" graphql:\"delete_countries_by_pk\""
	DeleteRegions                                       *RegionsMutationResponse                          "json:\"delete_regions,omitempty\" graphql:\"delete_regions\""
	DeleteRegionsByPk                                   *Regions                                          "json:\"delete_regions_by_pk,omitempty\" graphql:\"delete_regions_by_pk\""
	InsertApp                                           *Apps                                             "json:\"insertApp,omitempty\" graphql:\"insertApp\""
	InsertAppState                                      *AppStates                                        "json:\"insertAppState,omitempty\" graphql:\"insertAppState\""
	InsertAppStateHistories                             *AppStateHistoryMutationResponse                  "json:\"insertAppStateHistories,omitempty\" graphql:\"insertAppStateHistories\""
	InsertAppStateHistory                               *AppStateHistory                                  "json:\"insertAppStateHistory,omitempty\" graphql:\"insertAppStateHistory\""
	InsertAppStates                                     *AppStatesMutationResponse                        "json:\"insertAppStates,omitempty\" graphql:\"insertAppStates\""
	InsertApps                                          *AppsMutationResponse                             "json:\"insertApps,omitempty\" graphql:\"insertApps\""
	InsertAuthProvider                                  *AuthProviders                                    "json:\"insertAuthProvider,omitempty\" graphql:\"insertAuthProvider\""
	InsertAuthProviderRequest                           *AuthProviderRequests                             "json:\"insertAuthProviderRequest,omitempty\" graphql:\"insertAuthProviderRequest\""
	InsertAuthProviderRequests                          *AuthProviderRequestsMutationResponse             "json:\"insertAuthProviderRequests,omitempty\" graphql:\"insertAuthProviderRequests\""
	InsertAuthProviders                                 *AuthProvidersMutationResponse                    "json:\"insertAuthProviders,omitempty\" graphql:\"insertAuthProviders\""
	InsertAuthRefreshToken                              *AuthRefreshTokens                                "json:\"insertAuthRefreshToken,omitempty\" graphql:\"insertAuthRefreshToken\""
	InsertAuthRefreshTokens                             *AuthRefreshTokensMutationResponse                "json:\"insertAuthRefreshTokens,omitempty\" graphql:\"insertAuthRefreshTokens\""
	InsertAuthRole                                      *AuthRoles                                        "json:\"insertAuthRole,omitempty\" graphql:\"insertAuthRole\""
	InsertAuthRoles                                     *AuthRolesMutationResponse                        "json:\"insertAuthRoles,omitempty\" graphql:\"insertAuthRoles\""
	InsertAuthUserProvider                              *AuthUserProviders                                "json:\"insertAuthUserProvider,omitempty\" graphql:\"insertAuthUserProvider\""
	InsertAuthUserProviders                             *AuthUserProvidersMutationResponse                "json:\"insertAuthUserProviders,omitempty\" graphql:\"insertAuthUserProviders\""
	InsertAuthUserRole                                  *AuthUserRoles                                    "json:\"insertAuthUserRole,omitempty\" graphql:\"insertAuthUserRole\""
	InsertAuthUserRoles                                 *AuthUserRolesMutationResponse                    "json:\"insertAuthUserRoles,omitempty\" graphql:\"insertAuthUserRoles\""
	InsertAuthUserSecurityKey                           *AuthUserSecurityKeys                             "json:\"insertAuthUserSecurityKey,omitempty\" graphql:\"insertAuthUserSecurityKey\""
	InsertAuthUserSecurityKeys                          *AuthUserSecurityKeysMutationResponse             "json:\"insertAuthUserSecurityKeys,omitempty\" graphql:\"insertAuthUserSecurityKeys\""
	InsertBackup                                        *Backups                                          "json:\"insertBackup,omitempty\" graphql:\"insertBackup\""
	InsertBackups                                       *BackupsMutationResponse                          "json:\"insertBackups,omitempty\" graphql:\"insertBackups\""
	InsertBucket                                        *Buckets                                          "json:\"insertBucket,omitempty\" graphql:\"insertBucket\""
	InsertBuckets                                       *BucketsMutationResponse                          "json:\"insertBuckets,omitempty\" graphql:\"insertBuckets\""
	InsertCliToken                                      *CliTokens                                        "json:\"insertCliToken,omitempty\" graphql:\"insertCliToken\""
	InsertCliTokens                                     *CliTokensMutationResponse                        "json:\"insertCliTokens,omitempty\" graphql:\"insertCliTokens\""
	InsertConfig                                        ConfigInsertConfigResponse                        "json:\"insertConfig\" graphql:\"insertConfig\""
	InsertDeployment                                    *Deployments                                      "json:\"insertDeployment,omitempty\" graphql:\"insertDeployment\""
	InsertDeploymentLog                                 *DeploymentLogs                                   "json:\"insertDeploymentLog,omitempty\" graphql:\"insertDeploymentLog\""
	InsertDeploymentLogs                                *DeploymentLogsMutationResponse                   "json:\"insertDeploymentLogs,omitempty\" graphql:\"insertDeploymentLogs\""
	InsertDeployments                                   *DeploymentsMutationResponse                      "json:\"insertDeployments,omitempty\" graphql:\"insertDeployments\""
	InsertFeatureFlag                                   *FeatureFlags                                     "json:\"insertFeatureFlag,omitempty\" graphql:\"insertFeatureFlag\""
	InsertFeatureFlags                                  *FeatureFlagsMutationResponse                     "json:\"insertFeatureFlags,omitempty\" graphql:\"insertFeatureFlags\""
	InsertFeedback                                      *FeedbackMutationResponse                         "json:\"insertFeedback,omitempty\" graphql:\"insertFeedback\""
	InsertFeedbackOne                                   *Feedback                                         "json:\"insertFeedbackOne,omitempty\" graphql:\"insertFeedbackOne\""
	InsertFile                                          *Files                                            "json:\"insertFile,omitempty\" graphql:\"insertFile\""
	InsertFiles                                         *FilesMutationResponse                            "json:\"insertFiles,omitempty\" graphql:\"insertFiles\""
	InsertGithubAppInstallation                         *GithubAppInstallations                           "json:\"insertGithubAppInstallation,omitempty\" graphql:\"insertGithubAppInstallation\""
	InsertGithubAppInstallations                        *GithubAppInstallationsMutationResponse           "json:\"insertGithubAppInstallations,omitempty\" graphql:\"insertGithubAppInstallations\""
	InsertGithubRepositories                            *GithubRepositoriesMutationResponse               "json:\"insertGithubRepositories,omitempty\" graphql:\"insertGithubRepositories\""
	InsertGithubRepository                              *GithubRepositories                               "json:\"insertGithubRepository,omitempty\" graphql:\"insertGithubRepository\""
	InsertPaymentMethod                                 *PaymentMethods                                   "json:\"insertPaymentMethod,omitempty\" graphql:\"insertPaymentMethod\""
	InsertPaymentMethods                                *PaymentMethodsMutationResponse                   "json:\"insertPaymentMethods,omitempty\" graphql:\"insertPaymentMethods\""
	InsertPlan                                          *Plans                                            "json:\"insertPlan,omitempty\" graphql:\"insertPlan\""
	InsertPlans                                         *PlansMutationResponse                            "json:\"insertPlans,omitempty\" graphql:\"insertPlans\""
	InsertSecret                                        ConfigEnvironmentVariable                         "json:\"insertSecret\" graphql:\"insertSecret\""
	InsertUser                                          *Users                                            "json:\"insertUser,omitempty\" graphql:\"insertUser\""
	InsertUsers                                         *UsersMutationResponse                            "json:\"insertUsers,omitempty\" graphql:\"insertUsers\""
	InsertWorkspace                                     *Workspaces                                       "json:\"insertWorkspace,omitempty\" graphql:\"insertWorkspace\""
	InsertWorkspaceMember                               *WorkspaceMembers                                 "json:\"insertWorkspaceMember,omitempty\" graphql:\"insertWorkspaceMember\""
	InsertWorkspaceMemberInvite                         *WorkspaceMemberInvites                           "json:\"insertWorkspaceMemberInvite,omitempty\" graphql:\"insertWorkspaceMemberInvite\""
	InsertWorkspaceMemberInvites                        *WorkspaceMemberInvitesMutationResponse           "json:\"insertWorkspaceMemberInvites,omitempty\" graphql:\"insertWorkspaceMemberInvites\""
	InsertWorkspaceMembers                              *WorkspaceMembersMutationResponse                 "json:\"insertWorkspaceMembers,omitempty\" graphql:\"insertWorkspaceMembers\""
	InsertWorkspaces                                    *WorkspacesMutationResponse                       "json:\"insertWorkspaces,omitempty\" graphql:\"insertWorkspaces\""
	InsertAuthMigrations                                *AuthMigrationsMutationResponse                   "json:\"insert_auth_migrations,omitempty\" graphql:\"insert_auth_migrations\""
	InsertAuthMigrationsOne                             *AuthMigrations                                   "json:\"insert_auth_migrations_one,omitempty\" graphql:\"insert_auth_migrations_one\""
	InsertContinents                                    *ContinentsMutationResponse                       "json:\"insert_continents,omitempty\" graphql:\"insert_continents\""
	InsertContinentsOne                                 *Continents                                       "json:\"insert_continents_one,omitempty\" graphql:\"insert_continents_one\""
	InsertCountries                                     *CountriesMutationResponse                        "json:\"insert_countries,omitempty\" graphql:\"insert_countries\""
	InsertCountriesOne                                  *Countries                                        "json:\"insert_countries_one,omitempty\" graphql:\"insert_countries_one\""
	InsertRegions                                       *RegionsMutationResponse                          "json:\"insert_regions,omitempty\" graphql:\"insert_regions\""
	InsertRegionsOne                                    *Regions                                          "json:\"insert_regions_one,omitempty\" graphql:\"insert_regions_one\""
	MigrateRDSToPostgres                                bool                                              "json:\"migrateRDSToPostgres\" graphql:\"migrateRDSToPostgres\""
	PauseInactiveApps                                   []string                                          "json:\"pauseInactiveApps\" graphql:\"pauseInactiveApps\""
	ReplaceConfig                                       ConfigConfig                                      "json:\"replaceConfig\" graphql:\"replaceConfig\""
	ResetPostgresPassword                               bool                                              "json:\"resetPostgresPassword\" graphql:\"resetPostgresPassword\""
	RestoreApplicationDatabase                          bool                                              "json:\"restoreApplicationDatabase\" graphql:\"restoreApplicationDatabase\""
	UpdateApp                                           *Apps                                             "json:\"updateApp,omitempty\" graphql:\"updateApp\""
	UpdateAppState                                      *AppStates                                        "json:\"updateAppState,omitempty\" graphql:\"updateAppState\""
	UpdateAppStateHistories                             *AppStateHistoryMutationResponse                  "json:\"updateAppStateHistories,omitempty\" graphql:\"updateAppStateHistories\""
	UpdateAppStateHistory                               *AppStateHistory                                  "json:\"updateAppStateHistory,omitempty\" graphql:\"updateAppStateHistory\""
	UpdateAppStates                                     *AppStatesMutationResponse                        "json:\"updateAppStates,omitempty\" graphql:\"updateAppStates\""
	UpdateApps                                          *AppsMutationResponse                             "json:\"updateApps,omitempty\" graphql:\"updateApps\""
	UpdateAuthProvider                                  *AuthProviders                                    "json:\"updateAuthProvider,omitempty\" graphql:\"updateAuthProvider\""
	UpdateAuthProviderRequest                           *AuthProviderRequests                             "json:\"updateAuthProviderRequest,omitempty\" graphql:\"updateAuthProviderRequest\""
	UpdateAuthProviderRequests                          *AuthProviderRequestsMutationResponse             "json:\"updateAuthProviderRequests,omitempty\" graphql:\"updateAuthProviderRequests\""
	UpdateAuthProviders                                 *AuthProvidersMutationResponse                    "json:\"updateAuthProviders,omitempty\" graphql:\"updateAuthProviders\""
	UpdateAuthRefreshToken                              *AuthRefreshTokens                                "json:\"updateAuthRefreshToken,omitempty\" graphql:\"updateAuthRefreshToken\""
	UpdateAuthRefreshTokens                             *AuthRefreshTokensMutationResponse                "json:\"updateAuthRefreshTokens,omitempty\" graphql:\"updateAuthRefreshTokens\""
	UpdateAuthRole                                      *AuthRoles                                        "json:\"updateAuthRole,omitempty\" graphql:\"updateAuthRole\""
	UpdateAuthRoles                                     *AuthRolesMutationResponse                        "json:\"updateAuthRoles,omitempty\" graphql:\"updateAuthRoles\""
	UpdateAuthUserProvider                              *AuthUserProviders                                "json:\"updateAuthUserProvider,omitempty\" graphql:\"updateAuthUserProvider\""
	UpdateAuthUserProviders                             *AuthUserProvidersMutationResponse                "json:\"updateAuthUserProviders,omitempty\" graphql:\"updateAuthUserProviders\""
	UpdateAuthUserRole                                  *AuthUserRoles                                    "json:\"updateAuthUserRole,omitempty\" graphql:\"updateAuthUserRole\""
	UpdateAuthUserRoles                                 *AuthUserRolesMutationResponse                    "json:\"updateAuthUserRoles,omitempty\" graphql:\"updateAuthUserRoles\""
	UpdateAuthUserSecurityKey                           *AuthUserSecurityKeys                             "json:\"updateAuthUserSecurityKey,omitempty\" graphql:\"updateAuthUserSecurityKey\""
	UpdateAuthUserSecurityKeys                          *AuthUserSecurityKeysMutationResponse             "json:\"updateAuthUserSecurityKeys,omitempty\" graphql:\"updateAuthUserSecurityKeys\""
	UpdateBackup                                        *Backups                                          "json:\"updateBackup,omitempty\" graphql:\"updateBackup\""
	UpdateBackups                                       *BackupsMutationResponse                          "json:\"updateBackups,omitempty\" graphql:\"updateBackups\""
	UpdateBucket                                        *Buckets                                          "json:\"updateBucket,omitempty\" graphql:\"updateBucket\""
	UpdateBuckets                                       *BucketsMutationResponse                          "json:\"updateBuckets,omitempty\" graphql:\"updateBuckets\""
	UpdateCliToken                                      *CliTokens                                        "json:\"updateCliToken,omitempty\" graphql:\"updateCliToken\""
	UpdateCliTokens                                     *CliTokensMutationResponse                        "json:\"updateCliTokens,omitempty\" graphql:\"updateCliTokens\""
	UpdateConfig                                        ConfigConfig                                      "json:\"updateConfig\" graphql:\"updateConfig\""
	UpdateDeployment                                    *Deployments                                      "json:\"updateDeployment,omitempty\" graphql:\"updateDeployment\""
	UpdateDeploymentLog                                 *DeploymentLogs                                   "json:\"updateDeploymentLog,omitempty\" graphql:\"updateDeploymentLog\""
	UpdateDeploymentLogs                                *DeploymentLogsMutationResponse                   "json:\"updateDeploymentLogs,omitempty\" graphql:\"updateDeploymentLogs\""
	UpdateDeployments                                   *DeploymentsMutationResponse                      "json:\"updateDeployments,omitempty\" graphql:\"updateDeployments\""
	UpdateFeatureFlag                                   *FeatureFlags                                     "json:\"updateFeatureFlag,omitempty\" graphql:\"updateFeatureFlag\""
	UpdateFeatureFlags                                  *FeatureFlagsMutationResponse                     "json:\"updateFeatureFlags,omitempty\" graphql:\"updateFeatureFlags\""
	UpdateFeedback                                      *FeedbackMutationResponse                         "json:\"updateFeedback,omitempty\" graphql:\"updateFeedback\""
	UpdateFeedbackOne                                   *Feedback                                         "json:\"updateFeedbackOne,omitempty\" graphql:\"updateFeedbackOne\""
	UpdateFile                                          *Files                                            "json:\"updateFile,omitempty\" graphql:\"updateFile\""
	UpdateFiles                                         *FilesMutationResponse                            "json:\"updateFiles,omitempty\" graphql:\"updateFiles\""
	UpdateGithubAppInstallation                         *GithubAppInstallations                           "json:\"updateGithubAppInstallation,omitempty\" graphql:\"updateGithubAppInstallation\""
	UpdateGithubAppInstallations                        *GithubAppInstallationsMutationResponse           "json:\"updateGithubAppInstallations,omitempty\" graphql:\"updateGithubAppInstallations\""
	UpdateGithubRepositories                            *GithubRepositoriesMutationResponse               "json:\"updateGithubRepositories,omitempty\" graphql:\"updateGithubRepositories\""
	UpdateGithubRepository                              *GithubRepositories                               "json:\"updateGithubRepository,omitempty\" graphql:\"updateGithubRepository\""
	UpdatePaymentMethod                                 *PaymentMethods                                   "json:\"updatePaymentMethod,omitempty\" graphql:\"updatePaymentMethod\""
	UpdatePaymentMethods                                *PaymentMethodsMutationResponse                   "json:\"updatePaymentMethods,omitempty\" graphql:\"updatePaymentMethods\""
	UpdatePlan                                          *Plans                                            "json:\"updatePlan,omitempty\" graphql:\"updatePlan\""
	UpdatePlans                                         *PlansMutationResponse                            "json:\"updatePlans,omitempty\" graphql:\"updatePlans\""
	UpdateSecret                                        ConfigEnvironmentVariable                         "json:\"updateSecret\" graphql:\"updateSecret\""
	UpdateSystemConfig                                  ConfigSystemConfig                                "json:\"updateSystemConfig\" graphql:\"updateSystemConfig\""
	UpdateUser                                          *Users                                            "json:\"updateUser,omitempty\" graphql:\"updateUser\""
	UpdateUsers                                         *UsersMutationResponse                            "json:\"updateUsers,omitempty\" graphql:\"updateUsers\""
	UpdateWorkspace                                     *Workspaces                                       "json:\"updateWorkspace,omitempty\" graphql:\"updateWorkspace\""
	UpdateWorkspaceMember                               *WorkspaceMembers                                 "json:\"updateWorkspaceMember,omitempty\" graphql:\"updateWorkspaceMember\""
	UpdateWorkspaceMemberInvite                         *WorkspaceMemberInvites                           "json:\"updateWorkspaceMemberInvite,omitempty\" graphql:\"updateWorkspaceMemberInvite\""
	UpdateWorkspaceMemberInvites                        *WorkspaceMemberInvitesMutationResponse           "json:\"updateWorkspaceMemberInvites,omitempty\" graphql:\"updateWorkspaceMemberInvites\""
	UpdateWorkspaceMembers                              *WorkspaceMembersMutationResponse                 "json:\"updateWorkspaceMembers,omitempty\" graphql:\"updateWorkspaceMembers\""
	UpdateWorkspaces                                    *WorkspacesMutationResponse                       "json:\"updateWorkspaces,omitempty\" graphql:\"updateWorkspaces\""
	UpdateAppStateHistoryMany                           []*AppStateHistoryMutationResponse                "json:\"update_appStateHistory_many,omitempty\" graphql:\"update_appStateHistory_many\""
	UpdateAppStatesMany                                 []*AppStatesMutationResponse                      "json:\"update_appStates_many,omitempty\" graphql:\"update_appStates_many\""
	UpdateAppsMany                                      []*AppsMutationResponse                           "json:\"update_apps_many,omitempty\" graphql:\"update_apps_many\""
	UpdateAuthProviderRequestsMany                      []*AuthProviderRequestsMutationResponse           "json:\"update_authProviderRequests_many,omitempty\" graphql:\"update_authProviderRequests_many\""
	UpdateAuthProvidersMany                             []*AuthProvidersMutationResponse                  "json:\"update_authProviders_many,omitempty\" graphql:\"update_authProviders_many\""
	UpdateAuthRefreshTokensMany                         []*AuthRefreshTokensMutationResponse              "json:\"update_authRefreshTokens_many,omitempty\" graphql:\"update_authRefreshTokens_many\""
	UpdateAuthRolesMany                                 []*AuthRolesMutationResponse                      "json:\"update_authRoles_many,omitempty\" graphql:\"update_authRoles_many\""
	UpdateAuthUserProvidersMany                         []*AuthUserProvidersMutationResponse              "json:\"update_authUserProviders_many,omitempty\" graphql:\"update_authUserProviders_many\""
	UpdateAuthUserRolesMany                             []*AuthUserRolesMutationResponse                  "json:\"update_authUserRoles_many,omitempty\" graphql:\"update_authUserRoles_many\""
	UpdateAuthUserSecurityKeysMany                      []*AuthUserSecurityKeysMutationResponse           "json:\"update_authUserSecurityKeys_many,omitempty\" graphql:\"update_authUserSecurityKeys_many\""
	UpdateAuthMigrations                                *AuthMigrationsMutationResponse                   "json:\"update_auth_migrations,omitempty\" graphql:\"update_auth_migrations\""
	UpdateAuthMigrationsByPk                            *AuthMigrations                                   "json:\"update_auth_migrations_by_pk,omitempty\" graphql:\"update_auth_migrations_by_pk\""
	UpdateAuthMigrationsMany                            []*AuthMigrationsMutationResponse                 "json:\"update_auth_migrations_many,omitempty\" graphql:\"update_auth_migrations_many\""
	UpdateBackupsMany                                   []*BackupsMutationResponse                        "json:\"update_backups_many,omitempty\" graphql:\"update_backups_many\""
	UpdateBucketsMany                                   []*BucketsMutationResponse                        "json:\"update_buckets_many,omitempty\" graphql:\"update_buckets_many\""
	UpdateCliTokensMany                                 []*CliTokensMutationResponse                      "json:\"update_cliTokens_many,omitempty\" graphql:\"update_cliTokens_many\""
	UpdateContinents                                    *ContinentsMutationResponse                       "json:\"update_continents,omitempty\" graphql:\"update_continents\""
	UpdateContinentsByPk                                *Continents                                       "json:\"update_continents_by_pk,omitempty\" graphql:\"update_continents_by_pk\""
	UpdateContinentsMany                                []*ContinentsMutationResponse                     "json:\"update_continents_many,omitempty\" graphql:\"update_continents_many\""
	UpdateCountries                                     *CountriesMutationResponse                        "json:\"update_countries,omitempty\" graphql:\"update_countries\""
	UpdateCountriesByPk                                 *Countries                                        "json:\"update_countries_by_pk,omitempty\" graphql:\"update_countries_by_pk\""
	UpdateCountriesMany                                 []*CountriesMutationResponse                      "json:\"update_countries_many,omitempty\" graphql:\"update_countries_many\""
	UpdateDeploymentLogsMany                            []*DeploymentLogsMutationResponse                 "json:\"update_deploymentLogs_many,omitempty\" graphql:\"update_deploymentLogs_many\""
	UpdateDeploymentsMany                               []*DeploymentsMutationResponse                    "json:\"update_deployments_many,omitempty\" graphql:\"update_deployments_many\""
	UpdateFeatureFlagsMany                              []*FeatureFlagsMutationResponse                   "json:\"update_featureFlags_many,omitempty\" graphql:\"update_featureFlags_many\""
	UpdateFeedbackMany                                  []*FeedbackMutationResponse                       "json:\"update_feedback_many,omitempty\" graphql:\"update_feedback_many\""
	UpdateFilesMany                                     []*FilesMutationResponse                          "json:\"update_files_many,omitempty\" graphql:\"update_files_many\""
	UpdateGithubAppInstallationsMany                    []*GithubAppInstallationsMutationResponse         "json:\"update_githubAppInstallations_many,omitempty\" graphql:\"update_githubAppInstallations_many\""
	UpdateGithubRepositoriesMany                        []*GithubRepositoriesMutationResponse             "json:\"update_githubRepositories_many,omitempty\" graphql:\"update_githubRepositories_many\""
	UpdatePaymentMethodsMany                            []*PaymentMethodsMutationResponse                 "json:\"update_paymentMethods_many,omitempty\" graphql:\"update_paymentMethods_many\""
	UpdatePlansMany                                     []*PlansMutationResponse                          "json:\"update_plans_many,omitempty\" graphql:\"update_plans_many\""
	UpdateRegions                                       *RegionsMutationResponse                          "json:\"update_regions,omitempty\" graphql:\"update_regions\""
	UpdateRegionsByPk                                   *Regions                                          "json:\"update_regions_by_pk,omitempty\" graphql:\"update_regions_by_pk\""
	UpdateRegionsMany                                   []*RegionsMutationResponse                        "json:\"update_regions_many,omitempty\" graphql:\"update_regions_many\""
	UpdateUsersMany                                     []*UsersMutationResponse                          "json:\"update_users_many,omitempty\" graphql:\"update_users_many\""
	UpdateWorkspaceMemberInvitesMany                    []*WorkspaceMemberInvitesMutationResponse         "json:\"update_workspaceMemberInvites_many,omitempty\" graphql:\"update_workspaceMemberInvites_many\""
	UpdateWorkspaceMembersMany                          []*WorkspaceMembersMutationResponse               "json:\"update_workspaceMembers_many,omitempty\" graphql:\"update_workspaceMembers_many\""
	UpdateWorkspacesMany                                []*WorkspacesMutationResponse                     "json:\"update_workspaces_many,omitempty\" graphql:\"update_workspaces_many\""
	ZzzDonotuseDeleteBillingDedicatedCompute            *BillingDedicatedCompute                          "json:\"zzzDONOTUSE_delete_billing_dedicated_compute,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_dedicated_compute\""
	ZzzDonotuseDeleteBillingDedicatedComputeReport      *BillingDedicatedComputeReports                   "json:\"zzzDONOTUSE_delete_billing_dedicated_compute_report,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_dedicated_compute_report\""
	ZzzDonotuseDeleteBillingDedicatedComputeReports     *BillingDedicatedComputeReportsMutationResponse   "json:\"zzzDONOTUSE_delete_billing_dedicated_compute_reports,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_dedicated_compute_reports\""
	ZzzDonotuseDeleteBillingDedicatedComputes           *BillingDedicatedComputeMutationResponse          "json:\"zzzDONOTUSE_delete_billing_dedicated_computes,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_dedicated_computes\""
	ZzzDonotuseDeleteBillingSubscription                *BillingSubscriptions                             "json:\"zzzDONOTUSE_delete_billing_subscription,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_subscription\""
	ZzzDonotuseDeleteBillingSubscriptions               *BillingSubscriptionsMutationResponse             "json:\"zzzDONOTUSE_delete_billing_subscriptions,omitempty\" graphql:\"zzzDONOTUSE_delete_billing_subscriptions\""
	ZzzDonotuseInsertBillingDedicatedCompute            *BillingDedicatedCompute                          "json:\"zzzDONOTUSE_insert_billing_dedicated_compute,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_dedicated_compute\""
	ZzzDonotuseInsertBillingDedicatedComputeReport      *BillingDedicatedComputeReports                   "json:\"zzzDONOTUSE_insert_billing_dedicated_compute_report,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_dedicated_compute_report\""
	ZzzDonotuseInsertBillingDedicatedComputeReports     *BillingDedicatedComputeReportsMutationResponse   "json:\"zzzDONOTUSE_insert_billing_dedicated_compute_reports,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_dedicated_compute_reports\""
	ZzzDonotuseInsertBillingDedicatedComputes           *BillingDedicatedComputeMutationResponse          "json:\"zzzDONOTUSE_insert_billing_dedicated_computes,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_dedicated_computes\""
	ZzzDonotuseInsertBillingSubscription                *BillingSubscriptions                             "json:\"zzzDONOTUSE_insert_billing_subscription,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_subscription\""
	ZzzDonotuseInsertBillingSubscriptions               *BillingSubscriptionsMutationResponse             "json:\"zzzDONOTUSE_insert_billing_subscriptions,omitempty\" graphql:\"zzzDONOTUSE_insert_billing_subscriptions\""
	ZzzDonotuseUpdateBillingDedicatedCompute            *BillingDedicatedCompute                          "json:\"zzzDONOTUSE_update_billing_dedicated_compute,omitempty\" graphql:\"zzzDONOTUSE_update_billing_dedicated_compute\""
	ZzzDonotuseUpdateBillingDedicatedComputeReport      *BillingDedicatedComputeReports                   "json:\"zzzDONOTUSE_update_billing_dedicated_compute_report,omitempty\" graphql:\"zzzDONOTUSE_update_billing_dedicated_compute_report\""
	ZzzDonotuseUpdateBillingDedicatedComputeReports     *BillingDedicatedComputeReportsMutationResponse   "json:\"zzzDONOTUSE_update_billing_dedicated_compute_reports,omitempty\" graphql:\"zzzDONOTUSE_update_billing_dedicated_compute_reports\""
	ZzzDonotuseUpdateBillingDedicatedComputes           *BillingDedicatedComputeMutationResponse          "json:\"zzzDONOTUSE_update_billing_dedicated_computes,omitempty\" graphql:\"zzzDONOTUSE_update_billing_dedicated_computes\""
	ZzzDonotuseUpdateBillingSubscription                *BillingSubscriptions                             "json:\"zzzDONOTUSE_update_billing_subscription,omitempty\" graphql:\"zzzDONOTUSE_update_billing_subscription\""
	ZzzDonotuseUpdateBillingSubscriptions               *BillingSubscriptionsMutationResponse             "json:\"zzzDONOTUSE_update_billing_subscriptions,omitempty\" graphql:\"zzzDONOTUSE_update_billing_subscriptions\""
	ZzzDonotuseUpdateManyBillingDedicatedCompute        []*BillingDedicatedComputeMutationResponse        "json:\"zzzDONOTUSE_update_many_billing_dedicated_compute,omitempty\" graphql:\"zzzDONOTUSE_update_many_billing_dedicated_compute\""
	ZzzDonotuseUpdateManyBillingDedicatedComputeReports []*BillingDedicatedComputeReportsMutationResponse "json:\"zzzDONOTUSE_update_many_billing_dedicated_compute_reports,omitempty\" graphql:\"zzzDONOTUSE_update_many_billing_dedicated_compute_reports\""
	ZzzDonotuseUpdateManyBillingSubscriptions           []*BillingSubscriptionsMutationResponse           "json:\"zzzDONOTUSE_update_many_billing_subscriptions,omitempty\" graphql:\"zzzDONOTUSE_update_many_billing_subscriptions\""
}
type GetWorkspacesApps_Workspaces_Apps struct {
	Name string "json:\"name\" graphql:\"name\""
}

func (t *GetWorkspacesApps_Workspaces_Apps) GetName() string {
	if t == nil {
		t = &GetWorkspacesApps_Workspaces_Apps{}
	}
	return t.Name
}

type GetWorkspacesApps_Workspaces struct {
	Name string                               "json:\"name\" graphql:\"name\""
	Apps []*GetWorkspacesApps_Workspaces_Apps "json:\"apps\" graphql:\"apps\""
}

func (t *GetWorkspacesApps_Workspaces) GetName() string {
	if t == nil {
		t = &GetWorkspacesApps_Workspaces{}
	}
	return t.Name
}
func (t *GetWorkspacesApps_Workspaces) GetApps() []*GetWorkspacesApps_Workspaces_Apps {
	if t == nil {
		t = &GetWorkspacesApps_Workspaces{}
	}
	return t.Apps
}

type DeleteRefreshToken_DeleteAuthRefreshTokens_Returning struct {
	RefreshToken string "json:\"refreshToken\" graphql:\"refreshToken\""
}

func (t *DeleteRefreshToken_DeleteAuthRefreshTokens_Returning) GetRefreshToken() string {
	if t == nil {
		t = &DeleteRefreshToken_DeleteAuthRefreshTokens_Returning{}
	}
	return t.RefreshToken
}

type DeleteRefreshToken_DeleteAuthRefreshTokens struct {
	AffectedRows int64                                                   "json:\"affected_rows\" graphql:\"affected_rows\""
	Returning    []*DeleteRefreshToken_DeleteAuthRefreshTokens_Returning "json:\"returning\" graphql:\"returning\""
}

func (t *DeleteRefreshToken_DeleteAuthRefreshTokens) GetAffectedRows() int64 {
	if t == nil {
		t = &DeleteRefreshToken_DeleteAuthRefreshTokens{}
	}
	return t.AffectedRows
}
func (t *DeleteRefreshToken_DeleteAuthRefreshTokens) GetReturning() []*DeleteRefreshToken_DeleteAuthRefreshTokens_Returning {
	if t == nil {
		t = &DeleteRefreshToken_DeleteAuthRefreshTokens{}
	}
	return t.Returning
}

type GetWorkspacesApps struct {
	Workspaces []*GetWorkspacesApps_Workspaces "json:\"workspaces\" graphql:\"workspaces\""
}

func (t *GetWorkspacesApps) GetWorkspaces() []*GetWorkspacesApps_Workspaces {
	if t == nil {
		t = &GetWorkspacesApps{}
	}
	return t.Workspaces
}

type DeleteRefreshToken struct {
	DeleteAuthRefreshTokens *DeleteRefreshToken_DeleteAuthRefreshTokens "json:\"deleteAuthRefreshTokens,omitempty\" graphql:\"deleteAuthRefreshTokens\""
}

func (t *DeleteRefreshToken) GetDeleteAuthRefreshTokens() *DeleteRefreshToken_DeleteAuthRefreshTokens {
	if t == nil {
		t = &DeleteRefreshToken{}
	}
	return t.DeleteAuthRefreshTokens
}

const GetWorkspacesAppsDocument = `query GetWorkspacesApps {
	workspaces {
		name
		apps {
			name
		}
	}
}
`

func (c *Client) GetWorkspacesApps(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetWorkspacesApps, error) {
	vars := map[string]interface{}{}

	var res GetWorkspacesApps
	if err := c.Client.Post(ctx, "GetWorkspacesApps", GetWorkspacesAppsDocument, &res, vars, interceptors...); err != nil {
		return nil, err
	}

	return &res, nil
}

const DeleteRefreshTokenDocument = `mutation DeleteRefreshToken ($where: authRefreshTokens_bool_exp!) {
	deleteAuthRefreshTokens(where: $where) {
		affected_rows
		returning {
			refreshToken
		}
	}
}
`

func (c *Client) DeleteRefreshToken(ctx context.Context, where AuthRefreshTokensBoolExp, interceptors ...clientv2.RequestInterceptor) (*DeleteRefreshToken, error) {
	vars := map[string]interface{}{
		"where": where,
	}

	var res DeleteRefreshToken
	if err := c.Client.Post(ctx, "DeleteRefreshToken", DeleteRefreshTokenDocument, &res, vars, interceptors...); err != nil {
		return nil, err
	}

	return &res, nil
}
