# .github/workflows/build.yaml

name: Test & Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.5

      - name: Install Dependencies
        run: go get

      - name: Run Tests
        run: go test -timeout 30m -run ^Test_Pipeline$ github.com/${{ github.repository }}/cmd

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin 
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.5

      - name: Install Dependencies
        run: go get

      - name: Build Binary
        run: go build