---
name: "check and build"
on:
  pull_request:
  push:

jobs:
  tests:
    uses: ./.github/workflows/wf_check.yaml

  build_artifacts:
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      VERSION: ${{ github.sha }}
