---
name: "check and build"
on:
  pull_request:
  push:

jobs:
  tests:
    uses: ./.github/workflows/wf_check.yaml
    with:
      NAME: cli

  build_artifacts:
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      NAME: cli
      VERSION: ${{ github.sha }}
      ARCHS: '["aarch64","x86_64"]'
