# .github/workflows/release.yaml

name: Release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - published
  #push:
    #tags:
      #- '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.4
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  update-releases-file:
    name: Update Releases File
    runs-on: ubuntu-latest
    needs: releases-matrix
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          ref: gh-pages
      - name: Generate releases.json
        shell: bash
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh api repos/nhost/cli/releases > releases.json
      - name: Check if there are changes
        id: changes
        shell: bash
        run: |
          if [[ -z "$(git status --porcelain . )" ]]; then
           echo "::set-output name=changed::0"
          else
           echo "::set-output name=changed::1"
          fi
      - name: Committing releases.json
        shell: bash
        if: steps.changes.outputs.changed == 1
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "" --allow-empty-message
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.changes.outputs.changed == 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
