---
on:
  workflow_call:
    inputs:
      GIT_REF:
        type: string
        required: false
    secrets:
      NHOST_PAT:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.GIT_REF }}
        submodules: true

    - uses: cachix/install-nix-action@v27
      with:
        install_url: "https://releases.nixos.org/nix/nix-2.22.3/install"
        install_options: "--no-daemon"
        extra_nix_config: |
          experimental-features = nix-command flakes
          sandbox = false
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.nixos.org/?priority=40
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - uses: DeterminateSystems/magic-nix-cache-action@v7
      with:
        diagnostic-endpoint: ""
        use-flakehub: false

    - name: "Run checks"
      run: |
        export NHOST_PAT=${{ secrets.NHOST_PAT }}
        make check

    - name: "Cache nix store on s3"
      run: |
        echo ${{ secrets.NIX_CACHE_PRIV_KEY }} > cache-priv-key.pem
        nix store sign --key-file cache-priv-key.pem --all
        find /nix/store -maxdepth 1 -name "*-*" -type d | grep -v source | xargs -n 1000 nix copy --to s3://nhost-nix-cache\?region=eu-central-1
      if: always()
