---
on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

name: release
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.GIT_REF }}
          submodules: true

      - name: "Get artifacts"
        uses: actions/download-artifact@v4
        with:
          path: ~/artifacts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload docker images
        shell: bash
        run: |
          docker load < ~/artifacts/cli-docker-image-${{ inputs.VERSION }}-linux-amd64/result
          docker tag cli:${{ inputs.VERSION }} cli:${{ inputs.VERSION }}-amd64
          docker push cli:${{ inputs.VERSION }}-amd64

          docker load < ~/artifacts/cli-docker-image-${{ inputs.VERSION }}-linux-arm64/result
          docker tag cli:${{ inputs.VERSION }} cli:${{ inputs.VERSION }}-arm64
          docker push cli:${{ inputs.VERSION }}-arm64

          docker manifest create \
              cli:${{ inputs.VERSION }} \
              --amend $CONTAINER_NAME:${{ inputs.VERSION }}-amd64 \
              --amend $CONTAINER_NAME:${{ inputs.VERSION }}-arm64
          docker manifest push cli:${{ inputs.VERSION }}

      - name: Upload assets
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir upload
          tar cvzf ~/upload/cli-${{ inputs.VERSION }}-darwin-amd64.tar gz ~/artifacts/cli-${{ inputs.VERSION }}-darwin-amd64/nhost-cli
          tar cvzf ~/upload/cli-${{ inputs.VERSION }}-darwin-arm64.tar gz ~/artifacts/cli-${{ inputs.VERSION }}-darwin-arm64/nhost-cli
          tar cvzf ~/upload/cli-${{ inputs.VERSION }}-linux-amd64.tar gz ~/artifacts/cli-${{ inputs.VERSION }}-linux-amd64/nhost-cli
          tar cvzf ~/upload/cli-${{ inputs.VERSION }}-linux-arm64.tar gz ~/artifacts/cli-${{ inputs.VERSION }}-linux-arm64/nhost-cli
          find ~/upload/ -type f -exec sha256sum {} + > ~/upload/checksums.txt
          gh release upload \
            --clobber "${{ github.ref_name }}" \
            ./dist/*

